spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillbox
    username: postgres
    password: lovealmighty
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: create
